### ISSUE TITLE
User can browse films.

### ISSUE THREAD

**Issue by macyhongg** [macyhongg/ajax-project#1]
## 💰 Motivation
User can browse through Studio Ghibli films.

## 📐 Plan
Create a home page that allows users to browse through various Studio Ghibli films.

## 🖼️ Wireframes
<img width="268" alt="image" src="https://user-images.githubusercontent.com/94674653/189789964-65fbe559-d30e-4cc4-9f98-7e67923b7671.png">
<img width="694" alt="image" src="https://user-images.githubusercontent.com/94674653/189790056-cc72dc7f-46df-4cbb-ac35-753d6e623b45.png">

## ✅ Task List
- [x] Create an HTML Skeleton
- [x] Create a `new XMLHttpRequest()` object
- [x] `open()` the xhr object to send a 'GET' request to https://ghibliapi.herokuapp.com/films
- [x] Listen for the 'load' event on the `xhr` object
- [x] Ensure that the 'GET' request is successful:
 - [x] Log the **status** of the `xhr` object to the console
 - [x] Log the **response** of the `xhr` object to the console
- [x] For each object in the response, create a new film card containing the title, image, and description
- [x] Append film card to the main page
- [x] Ensure that the page looks nice on both mobile-sized and desktop-sized screens
- **Clean Up**
  - [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
  - [x] Remove all console logs and commented out code.
  - [x] Test all functionality again in a private browsing session.
  - [x] Fix all errors.
