### ISSUE TITLE
User can view details of a film

### ISSUE THREAD

**Issue by macyhongg** [macyhongg/ajax-project#2]
## 💰 Motivation
When user clicks on a film from the browsing page, they will be able to see details of a specific film.

## 📐 Plan
Create a page that shows a detailed view of a selected film.

## 🖼️ Wireframes
<img width="280" alt="image" src="https://user-images.githubusercontent.com/94674653/189790748-37535aac-a8a9-4c03-9426-a467b536e750.png">
<img width="699" alt="image" src="https://user-images.githubusercontent.com/94674653/189790615-05a4a680-e506-48c3-8b3e-4ddb865a0cad.png">

## ✅ Task List
- [x] Listen for clicks on the film title or picture
- [x] Create an HTML skeleton for what user will see when they click on a film for more details
- [ ] Ensure that the styling and spacing of the Details page look good
- [ ] Set up view swapping to hide main page and show Details page
- [ ] Clean up:
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
