### ISSUE TITLE
User can save a film

### ISSUE THREAD

**Issue by macyhongg** [macyhongg/ajax-project#3]
## 💰 Motivation
User can save a film to their To-Watch List

## 📐 Plan
Create functionality so that the site will recognize when a film has been saved, and add it to a list.

## 🖼️ Wireframes
<img width="279" alt="image" src="https://user-images.githubusercontent.com/94674653/189791087-fd75e9c6-85cc-4320-bd22-e7c0598d681d.png">
<img width="699" alt="image" src="https://user-images.githubusercontent.com/94674653/189790615-05a4a680-e506-48c3-8b3e-4ddb865a0cad.png">

## ✅ Task List
- [ ] 
- [ ] Clean up:
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
