### ISSUE TITLE
User can view all saved films

### ISSUE THREAD

**Issue by macyhongg** [macyhongg/ajax-project#4]
## 💰 Motivation
User can view all saved films

## 📐 Plan
Display all saved films at once

## 🖼️ Wireframes
<img width="274" alt="image" src="https://user-images.githubusercontent.com/94674653/189791482-d67d29f9-e8e3-4eab-98cd-fd58a1fa10a2.png">
<img width="719" alt="image" src="https://user-images.githubusercontent.com/94674653/189791505-2bd371c2-cb3b-43a0-b097-19ebd01014da.png">

## ✅ Task List
- [ ] Create a new display
- [ ] Clean up:
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
